In [2]:
import numpy as np

# Задание 1

In [16]:
N = 10

print(np.flip(np.arange(N)))

[9 8 7 6 5 4 3 2 1 0]


# Задание 2

In [20]:
N = 10

v = np.flip(np.arange(N))
d = np.diag(v)

print("SUM = {}".format(np.trace(d)))

print(d)

SUM = 45
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


# Задание 3

In [21]:
# 4x + 2y + z  =  4
#  x + 3y      = 12
#      5y + 4z = -3

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

x = np.linalg.solve(a, b)

print(x)

[ 0.46666667  3.84444444 -5.55555556]


# Задание 4

In [32]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

print(max(map(lambda x: cosine(x, next_user_stats), users_stats)))

0.9486832980505138
