# Классификация: Логистическая регрессия и SVM

In [1]:
import numpy as np
import pandas as pd

# from sklearn import datasets, linear_model, model_selection
# from sklearn.model_selection import train_test_split

In [2]:
# http://www.cs.toronto.edu/~delve/data/adult/adultDetail.html
    
df = pd.read_csv('adult.csv', na_values=['?'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        46043 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       46033 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   47985 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


Бдуем строить на основе признаков age, educational-num, occupation, race, gender, hours-per-week, native-country. Убираем пустые значения

In [3]:
df = df[ pd.isnull( df['age'] ) == 0 ]
df = df[ pd.isnull( df['educational-num'] ) == 0 ]
df = df[ pd.isnull( df['occupation'] ) == 0 ]
df = df[ pd.isnull( df['gender'] ) == 0 ]
df = df[ pd.isnull( df['hours-per-week'] ) == 0 ]
df = df[ pd.isnull( df['native-country'] ) == 0 ]

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45222 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              45222 non-null  int64 
 1   workclass        45222 non-null  object
 2   fnlwgt           45222 non-null  int64 
 3   education        45222 non-null  object
 4   educational-num  45222 non-null  int64 
 5   marital-status   45222 non-null  object
 6   occupation       45222 non-null  object
 7   relationship     45222 non-null  object
 8   race             45222 non-null  object
 9   gender           45222 non-null  object
 10  capital-gain     45222 non-null  int64 
 11  capital-loss     45222 non-null  int64 
 12  hours-per-week   45222 non-null  int64 
 13  native-country   45222 non-null  object
 14  income           45222 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.5+ MB


In [22]:
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
5   34    Private  198693          10th                6       Never-married   

          occupation   relationship   race gender  capital-gain  capital-loss  \
0  Machine-op-inspct      Own-child  Black   Male             0             0   
1    Farming-fishing        Husband  White   Male             0             0   
2    Protective-serv        Husband  White   Male             0             0   
3  Machine-op-inspct        Husband  Black   Male          7688             0   
5      Other-service  Not-in-family  White   Male             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
5              30  United-States  <=50K

In [4]:
from sklearn.preprocessing import StandardScaler

In [13]:
data = df[['age', 'educational-num', 'occupation', 'gender', 'hours-per-week', 'native-country']]

X_not_scaled = pd.get_dummies(data, columns = ['occupation', 'gender', 'native-country'])

sc = StandardScaler()

X = sc.fit_transform(X_not_scaled)

X

array([[-1.02498291, -1.22155881, -0.07812006, ...,  0.30850579,
        -0.04288082, -0.02255794],
       [-0.04145504, -0.43812161,  0.7547014 , ...,  0.30850579,
        -0.04288082, -0.02255794],
       [-0.79801494,  0.73703421, -0.07812006, ...,  0.30850579,
        -0.04288082, -0.02255794],
       ...,
       [ 1.47166476, -0.43812161, -0.07812006, ...,  0.30850579,
        -0.04288082, -0.02255794],
       [-1.25195088, -0.43812161, -1.74376299, ...,  0.30850579,
        -0.04288082, -0.02255794],
       [ 1.01772882, -0.43812161, -0.07812006, ...,  0.30850579,
        -0.04288082, -0.02255794]])

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit( df['income'] )

y = pd.Series( data = le.transform( df['income'] ) )

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [11]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=5000)
model.fit( x_train, y_train )

LogisticRegression(max_iter=5000)

In [15]:
model.predict_proba(x_test)

array([[0.98870859, 0.01129141],
       [0.91009979, 0.08990021],
       [0.63263073, 0.36736927],
       ...,
       [0.93222751, 0.06777249],
       [0.97475376, 0.02524624],
       [0.33038282, 0.66961718]])

In [12]:
model.score(x_test, y_test)

0.8040834377533721

# SVM

признаков больше 2-х, поэтому хз как график построить для данного случая

In [30]:
from sklearn.svm import SVC

In [31]:
svc = SVC()
svc.fit(x_train, y_train)

SVC()

In [34]:
svc.predict(x_test)

array([0, 0, 0, ..., 0, 0, 1])

In [36]:
svc.score(x_test, y_test)

0.8072528930493108